// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOte_KhCDNqi0bYboEo52k8kXwy5CgFnE',
    appId: '1:270607569723:web:eee5e8fd12b07ee7461d1e',
    messagingSenderId: '270607569723',
    projectId: 'personal-diaries-8acf3',
    authDomain: 'personal-diaries-8acf3.firebaseapp.com',
    storageBucket: 'personal-diaries-8acf3.firebasestorage.app',
    measurementId: 'G-GQGZ6GLBBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa9J0G6hGDgQK52oLzgcJr-bc6voMQ_7U',
    appId: '1:270607569723:android:392d25afc5d04526461d1e',
    messagingSenderId: '270607569723',
    projectId: 'personal-diaries-8acf3',
    storageBucket: 'personal-diaries-8acf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBeIZMtbQDsU5hTLfW5StQ26Uf1peDcUI',
    appId: '1:270607569723:ios:cb890f24afac5feb461d1e',
    messagingSenderId: '270607569723',
    projectId: 'personal-diaries-8acf3',
    storageBucket: 'personal-diaries-8acf3.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBeIZMtbQDsU5hTLfW5StQ26Uf1peDcUI',
    appId: '1:270607569723:ios:cb890f24afac5feb461d1e',
    messagingSenderId: '270607569723',
    projectId: 'personal-diaries-8acf3',
    storageBucket: 'personal-diaries-8acf3.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOte_KhCDNqi0bYboEo52k8kXwy5CgFnE',
    appId: '1:270607569723:web:bfc67515a40a6645461d1e',
    messagingSenderId: '270607569723',
    projectId: 'personal-diaries-8acf3',
    authDomain: 'personal-diaries-8acf3.firebaseapp.com',
    storageBucket: 'personal-diaries-8acf3.firebasestorage.app',
    measurementId: 'G-JMMCSGH41Q',
  );
}
