// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your API Key',
    appId: 'Your App ID',
    messagingSenderId: 'Your ID',
    projectId: 'Your Firebase Console Project Path',
    authDomain: 'yourauthdomain',
    storageBucket: 'your storage',
    measurementId: 'your id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: 'your IDs',
    projectId: 'your firebases project path',
    storageBucket: 'your storagebucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your API KEY',
    appId: 'Your App Key',
    messagingSenderId: 'Your IDs',
    projectId: 'Your Firebase Project',
    storageBucket: 'Your Blahhh blahhh',
    iosBundleId: 'Blah Blahhhh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Similarly same',
    appId: 'similarly same',
    messagingSenderId: 'same ids',
    projectId: 'same ids',
    storageBucket: 'ids',
    iosBundleId: 'ids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'haha i am bored',
    appId: 'ENjoy',
    messagingSenderId: 'Dont look this',
    projectId: 'this is not good brother',
    authDomain: 'haha',
    storageBucket: 'Hello',
    measurementId: 'ABCD',
  );
}
